version: '3.3'

services:
  express-app:
    container_name: express-app
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - '2000:2000'
    depends_on:
      - mySqlCont
    environment:
      DATABASE_URL: mysql://root:mypassword@mySqlCont:1002/mitraindb
      PORT: 2000
      JWT_SECRET: diuwahiuwahdaiu23133212uihdwa

  mySqlCont:
    image: mysql:latest
    container_name: mySqlCont
    restart: always
    command: --port=1002
    environment:
      MYSQL_ROOT_PASSWORD: mypassword  # Set root password
      MYSQL_DATABASE: mitraindb
      # MYSQL_USER: user
      # MYSQL_ROOT_PASSWORD: mypassword
      # MYSQL_PASSWORD: mypassword
      # MYSQL_DATABASE: mitraindb
    volumes:
      - mitrain-db:/var/lib/mysql
    ports:
      - '1002:1002'

volumes:
  mitrain-db:
